const HomeCard = require('./HomeCard');
const NewBotTokenCard = require('./NewBotTokenCard');
const AboutCard = require('./AboutCard');
const AccountCard = require('./AccountCard');
const BotSetupCard = require('./BotSetupCard');
const BotAutomationsCard = require('./BotAutomationsCard');
const { UsersManagementCard } = require('./UsersManagementCard');
const { NewDeploymentIdCard } = require('./NewDeploymentIdCard');
const { SetMyChatIdCard } = require('./SetMyChatIdCard');

global.SetMyChatIdCard = SetMyChatIdCard;
global.NewDeploymentIdCard = NewDeploymentIdCard;
global.UsersManagementCard = UsersManagementCard;
global.HomeCard = HomeCard;
global.NewBotTokenCard = NewBotTokenCard;
global.AboutCard = AboutCard;
global.AccountCard = AccountCard;
global.BotSetupCard = BotSetupCard;
global.BotAutomationsCard = BotAutomationsCard;
